tag: adhoc
history:
    adhocBranchName: __for_merging--beta-next--16.0.9316.5452--2018-04-17--3.50pm
    commitMessage: __for_merging--beta-next--16.0.9316.5452--2018-04-17--3.50pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6334d39aa627071076c8c3e1f270d4b7fbba403f
            message: >-
                JS dist files --
                __for_merging--beta-next--16.0.9316.5452--2018-04-17--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/b784d56caa40130e70d7c98db0a236494e7d8cc5
            message: >-
                Localized strings --
                __for_merging--beta-next--16.0.9316.5452--2018-04-17--3.50pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/75106a7722fabfbd63e37322fc59fcd35c79c801
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a68186fc03bc4acf02eb6f6210512d7ec21732f2
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/12cf468441a40422f649ef2b872b385500553c1a
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __for_merging--beta-next--16.0.9316.5452--2018-04-17--3.50pm
