version: 1.1.9-beta.0
tag: beta
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.9-beta.0
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.9-beta.0
deployedAt: 2018-09-20 10:59 pm UTC  (2018-09-20 3:59 pm Pacific Time)

history:
    adhocBranchName: __for_merging--beta--16.0.10917.35450--2018-09-20--3.45pm
    commitMessage: __for_merging--beta--16.0.10917.35450--2018-09-20--3.45pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4a087e720cde7989784e87784c2b5136c3e3237e
            message: >-
                JS dist files --
                __for_merging--beta--16.0.10917.35450--2018-09-20--3.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4d9d45cd6c62815591947b3fdb36bc0c1672e9a1
            message: >-
                Localized strings --
                __for_merging--beta--16.0.10917.35450--2018-09-20--3.45pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4d497091bc8a25efacc5e551012c7eee3c4e97d8
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/1645111122a41a88170a33e17064282d31defdc0
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/d0093831ce0cfacfe12d7ab24fce359f9e1b9fda
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __for_merging--beta--16.0.10917.35450--2018-09-20--3.45pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.9-beta.0/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.9-beta.0/dist/office.d.ts
    builds using this same tag ("beta"):
        https://unpkg.com/@microsoft/office-js@beta/dist/office.js
        https://unpkg.com/@microsoft/office-js@beta/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/431264400