tag: adhoc
history:
    adhocBranchName: __adhoc--release--16.0.9228.5452--2018-04-15--2.03pm
    commitMessage: __adhoc--release--16.0.9228.5452--2018-04-15--2.03pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/95107849ba1b9d6dbd0aa87b45aba27277965e70
            message: >-
                JS dist files --
                __adhoc--release--16.0.9228.5452--2018-04-15--2.03pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/4ebb08515578cb2e99700b9c318cbd7fa68532b4
            message: >-
                Localized strings --
                __adhoc--release--16.0.9228.5452--2018-04-15--2.03pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/dd994116022d4ee1406617a5b439d68e4ca34ced
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/08f8ec556d1016d4a4e5e1c58cf539feff2f6362
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/35b4e758db96157a14fd7fdc3adeb5e87e00ae63
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--release--16.0.9228.5452--2018-04-15--2.03pm
