version: 1.1.5-beta-next.1
tag: beta-next
githubReleaseUrl: https://github.com/OfficeDev/office-js/releases/tag/v1.1.5-beta-next.1
githubViewUrl: https://github.com/OfficeDev/office-js/tree/v1.1.5-beta-next.1
deployedAt: 2018-04-15 10:48 pm UTC  (2018-04-15 3:48 pm Pacific Time)

history:
    adhocBranchName: __adhoc--beta-next--16.0.9315.5450--2018-04-15--3.30pm
    commitMessage: __adhoc--beta-next--16.0.9315.5450--2018-04-15--3.30pm
    fullCommitHistory:
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/a0040658b8ccaa1d2911b73b46029951704a305c
            message: >-
                JS dist files --
                __adhoc--beta-next--16.0.9315.5450--2018-04-15--3.30pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6bf06adf60c1cac78c0df46ab80c14f9810258c5
            message: >-
                Localized strings --
                __adhoc--beta-next--16.0.9315.5450--2018-04-15--3.30pm
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/6e36f38959d8f82f1236f66acd4c7c60d0bfacf1
            message: Copying other assets from the release branch of the repo
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/9e1e282dfd24cc5cd27d763d258531f6cd77d4a8
            message: >-
                [PUBLISH TOOL] Add deployment infrastructure for adhoc NPM
                publish
        - 
            sha: >-
                https://github.com/OfficeDev/office-js/commits/3131ef870a9f1f150dbf10e6f006f48e75b93191
            message: >-
                [BEGIN PUBLISH UPDATES] --
                __adhoc--beta-next--16.0.9315.5450--2018-04-15--3.30pm


unpkgUrls: |-
    this specific build number:
        https://unpkg.com/@microsoft/office-js@1.1.5-beta-next.1/dist/office.js
        https://unpkg.com/@microsoft/office-js@1.1.5-beta-next.1/dist/office.d.ts
    builds using this same tag ("beta-next"):
        https://unpkg.com/@microsoft/office-js@beta-next/dist/office.js
        https://unpkg.com/@microsoft/office-js@beta-next/dist/office.d.ts

buildLog: https://travis-ci.org/OfficeDev/office-js/builds/366925765